### PR TITLE
user endpoints added, teamMember table name updated and seeded users …

### PR DESCRIPTION
**Pull request by erinc35**

### CODE REVIEW

**Review by farste — APPROVED** [review]
Confirmed ability to pull users and team members from db

**Comment by erinc35** [comment]
[BE - Setup route / endpoint to pull user data](https://trello.com/c/zl0NxRmT/49-be-setup-route-endpoint-to-pull-user-data)

**Comment by ChelseaTolnai** [comment]
[BE - Setup initial Route directory](https://trello.com/c/A9OyKLE2/41-be-setup-initial-route-directory)

**Comment by adrianadames** [comment]
[BE - Setup initial knex db, migrations, seeds](https://trello.com/c/CTNvB48H/43-be-setup-initial-knex-db-migrations-seeds)

**Pull request merged**
